run:
  timeout: 5m
  skip-dirs:
    - pkg/generated
    - go
  skip-files: [zz_generated.deepcopy.go]

linters:
  # Enable all linters
  presets:
    - bugs
    - complexity
    - format
    - performance
    - style
    - unused

  # Selectively disable things to get a pass.  These probably are
  # masking bugs so re-enable and fix them!
  # These disables were copied over directly from Operator.  We should remove them and
  # see fix any issues discovered.
  disable:
    - gosec # insecure!
    - nestif # complicated code
    - gomnd # magic numbers
    - testpackage # packages for test, need to be marked as test
    - gocognit # complicated functions
    - gocyclo # complicated functions
    - godox # TODOs are bad, it suggests it's not finished
    - maligned # memory alignment - this is fine
    - funlen # complicated functions
    - gochecknoglobals # global variables
    - lll # long lines
    - gochecknoinits # init functions
    - goconst # repeated things that should be constants
    - prealloc # constant sized arrays can be preallocated
    - nakedret # using naked returns in complicated functions
    - exhaustive # doesn't pay attention to default in switch statements
    - exhaustivestruct # it's okay not to define every field
    - gofumpt # really anal
    - paralleltest # really really anal
    - nlreturn # seems at odds with cuddling
    - noctx # do want to fix this
    - wrapcheck # we do want this, but I want https://github.com/tomarrell/wrapcheck/issues/2 fixing first
    - tagliatelle # This chokes on Couchbase Server Models that cannot be changed

linters-settings:
  # Code duplication filter catches a lot of duplication in test
  # this needs refactoring at some point.
  dupl:
    threshold: 500
  cyclop:
    max-complexity: 25
issues:
  exclude-rules:
    # Deep copies have 'in' as the receiver, ours have something else.
    # This linter should ignore the auto generated stuff, but doesn't.
    - text: ST1016
      linters:
        - stylecheck
    # Things that are parameterized, and don't need to be.  This is probably
    # a gap in testing.
    - text: always receives
      linters:
        - unparam
    # Test is exempt from proper error handling.
    - path: test/.*
      linters:
        - goerr113
